BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Peeps" (
	"Name"	TEXT NOT NULL UNIQUE,
	"Gender"	NUMERIC NOT NULL,
	"Age"	NUMERIC NOT NULL,
	"Prego"	NUMERIC NOT NULL,
	"Married"	NUMERIC NOT NULL,
	"BIT0"	NUMERIC NOT NULL,
	"BIT1"	NUMERIC NOT NULL,
	"BIT2"	NUMERIC NOT NULL,
	"BIT3"	NUMERIC NOT NULL,
	"BIT4"	NUMERIC NOT NULL,
	"BIT5"	NUMERIC NOT NULL,
	"BIT6"	NUMERIC NOT NULL,
	"BIT7"	NUMERIC NOT NULL,
	"BIT8"	NUMERIC NOT NULL,
	"BIT9"	NUMERIC NOT NULL,
	"BITA"	NUMERIC NOT NULL,
	"BITB"	NUMERIC NOT NULL,
	"BITC"	NUMERIC NOT NULL,
	"BITD"	NUMERIC NOT NULL,
	"BITE"	NUMERIC NOT NULL,
	"BITF"	NUMERIC NOT NULL,
	PRIMARY KEY("Name","Gender")
);
CREATE INDEX IF NOT EXISTS "NameIDX" ON "Peeps" (
	"Name"	ASC,
	"Gender",
	"Age"
);
CREATE INDEX IF NOT EXISTS "PregoIDX" ON "Peeps" (
	"Name"	ASC,
	"Gender",
	"Married",
	"Prego"
);
CREATE INDEX IF NOT EXISTS "AgeIDX" ON "Peeps" (
	"Age",
	"Name"
);
COMMIT;
